site_name: spyral-utils
site_url: https://example.com/
repo_url: https://github.com/gwm17/spyral-utils/
site_description: Documentaion for the sypral-utils package

nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - API Documentaion:
    - About: api/about.md
    - Constants: api/constants.md
    - Nuclear:
      - Module Overview: api/nuclear/index.md
      - Momentum Module: api/nuclear/momentum.md
      - Nuclear Mass Module: api/nuclear/nuclear_map.md
      - Target Material Module: api/nuclear/target.md
    - Plotting:
      - Module Overview: api/plot/index.md
      - Histogram Module: api/plot/histogram.md
      - Cut Module: api/plot/cut.md
  - FAQ: faq.md
  - For Developers: for_devs.md

theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          allow_inspection: true
          docstring_style: numpy
