name: CI 
run-name: ${{ github.actor }} running CI 
on:
  push:
    branches:
      - '*'
      - '!gh-pages'
jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12']
                os: [ubuntu-latest, macOS-latest, windows-latest]
        steps:
            - uses: actions/checkout@v4
            - name: Set up PDM
              uses: pdm-project/setup-pdm@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                pdm sync -d
            - name: Run tests
              run: |
                pdm run -v pytest tests

    check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Setup PDM
          uses: pdm-project/setup-pdm@v4
          with:
            python-version: '3.12'
        - name: Install deps
          run: |
            pdm sync -d
        - name: Lint code 
          run: |
            pdm run ruff check 
        - name: Check formatting
          run: |
            pdm run ruff format --check 

