name: release-pypi
run-name: ${{ github.actor }} publishing to PyPI
on:
    release:
        types:
            - released
jobs:
    pypi-publish:
        name: upload release to PyPI
        runs-on: ubuntu-latest
        environment: release-pypi
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: pdm-project/setup-pdm@v4
            - name: Publish packages to PyPI
              run: pdm publish
